FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

# copy csproj and restore as distinct layers
COPY ./src/Candidate.Api/Candidate.Api.csproj ./Candidate.Api/
RUN dotnet restore Candidate.Api/Candidate.Api.csproj

# copy everything else and build
COPY ./src/ .
WORKDIR /Candidate.Api/
RUN dotnet publish -c $BUILDCONFIG -r alpine-x64 --self-contained true /p:PublishTrimmed=true -o out /p:Version=$VERSION

# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
WORKDIR /app
COPY --from=build /Candidate.Api/out ./

EXPOSE 80 5000

ENTRYPOINT ["dotnet", "Candidate.Api.dll"]